repos:
-   repo: local
    hooks:
      - id: ruff-check
        name: Ruff check
        entry: poetry run ruff check
        args: [ --fix, --extend-select, I ]
        language: system
        types: [ python ]
      - id: ruff-format
        name: Ruff format
        entry: poetry run ruff format .
        language: system
        types: [ python ]
      - id: pyright
        name: Pyright
        entry: poetry run pyright
        language: system
        pass_filenames: true
        types: [ python ]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
